# Set-Wifi.ps1 - one-time setup for ESP8266 Anywhere Control
# Asks for WiFi name, WiFi password and Blynk Auth Token, writes secrets.h,
# then compiles + uploads the firmware. Password/token never go into GitHub.
param(
  [switch]$NoPause
)

$ErrorActionPreference = "Stop"
$CLI   = "C:\Users\Public\arduino-cli.exe"
$BUILD = "C:\Users\Public\esp8266-anywhere-control"
$WSL   = "\\wsl.localhost\Ubuntu\home\salman\arduino-projects\projects\esp8266-anywhere-control"
$FQBN  = "esp8266:esp8266:nodemcuv2"

function Fail($msg) {
  Write-Host ""
  Write-Host "ERROR: $msg" -ForegroundColor Red
  if (-not $NoPause) { Read-Host "Press Enter to close" }
  exit 1
}

function Esc($s) {
  # escape for a C string literal
  return $s.Replace('\', '\\').Replace('"', '\"')
}

Write-Host "=============================================="
Write-Host " ESP8266 Anywhere Control - one-time WiFi setup"
Write-Host "=============================================="
Write-Host ""
Write-Host "Where to get the Blynk Auth Token:"
Write-Host "  https://blynk.cloud  ->  Devices  ->  your device"
Write-Host "  ->  Developer Tools  ->  Device Info  ->  Auth Token"
Write-Host "  (create the device first if you have none)"
Write-Host ""

$ssid  = (Read-Host "1) WiFi name (SSID)").Trim()
$pass  = (Read-Host "2) WiFi password").Trim()
$token = (Read-Host "3) Blynk Auth Token").Trim()

if ($ssid -eq "")  { Fail "WiFi name is empty." }
if ($pass -eq "")  { Fail "WiFi password is empty." }
if ($token -eq "") { Fail "Blynk Auth Token is empty." }

# A real Blynk Auth Token is exactly 32 alphanumeric characters, no spaces.
if ($token -notmatch '^[A-Za-z0-9]{32}$') {
  Fail ("Auth Token looks wrong (you entered " + $token.Length + " characters).`r`n" +
        "It must be exactly 32 letters/numbers, no spaces.`r`n`r`n" +
        "Re-copy it: blynk.cloud -> Devices -> your device`r`n" +
        "          -> Developer Tools -> Device Info -> Auth Token")
}
if ($pass.Length -lt 8 -or $pass.Length -gt 63) {
  Fail ("WiFi password length is " + $pass.Length + " - WPA2 passwords are 8 to 63 characters.`r`n" +
        "Check it wasn't cut short when you typed/pasted it.")
}

$body = @"
/*
  secrets.h - generated by Set WiFi.bat on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
  This file is listed in .gitignore and is NEVER uploaded to GitHub.
*/
#define BLYNK_PROV_SSID   "$(Esc $ssid)"
#define BLYNK_PROV_PASS   "$(Esc $pass)"
#define BLYNK_PROV_TOKEN  "$(Esc $token)"
"@

Set-Content -Path "$BUILD\secrets.h" -Value $body -Encoding ASCII
Write-Host ""
Write-Host "secrets.h written to: $BUILD\secrets.h" -ForegroundColor Green

if (Test-Path $WSL) {
  Set-Content -Path "$WSL\secrets.h" -Value $body -Encoding ASCII
  Write-Host "secrets.h written to: $WSL\secrets.h" -ForegroundColor Green
}

# find the COM port
Write-Host ""
Write-Host "Looking for the board..." -ForegroundColor Cyan
$list = & $CLI board list --discovery-timeout 5s 2>&1 | Out-String
$port = $null
foreach ($line in ($list -split "`r?`n")) {
  if ($line -match '(COM\d+)') { $port = $Matches[1]; break }
}
if (-not $port) {
  Write-Host $list
  Fail "No board found. Unplug the USB cable, wait 3 seconds, plug it back in, then run this again."
}
Write-Host "Board found on $port" -ForegroundColor Green

Write-Host ""
Write-Host "Compiling..." -ForegroundColor Cyan
& $CLI compile -b $FQBN $BUILD 2>&1 | ForEach-Object {
  $t = "$_"
  if ($t -match 'error|Error') { Fail $t }
  if ($t -match 'Sketch uses|Global variables') { Write-Host $t }
}
if ($LASTEXITCODE -ne 0) { Fail "Compilation failed - see messages above." }

Write-Host ""
Write-Host "Uploading to $port ..." -ForegroundColor Cyan
& $CLI upload -p $port -b $FQBN $BUILD 2>&1 | Select-Object -Last 3
if ($LASTEXITCODE -ne 0) { Fail "Upload failed. Unplug/replug the USB cable and run again." }

Write-Host ""
Write-Host "Reading board output for 30 seconds..." -ForegroundColor Cyan
Start-Sleep -Milliseconds 500
$s = New-Object System.IO.Ports.SerialPort $port,115200,None,8,One
$s.DtrEnable = $true
$s.RtsEnable = $true
$s.ReadTimeout = 1000
try { $s.Open() } catch { Fail "Could not open ${port}: $($_.Exception.Message)" }
$end = (Get-Date).AddSeconds(30)
while ((Get-Date) -lt $end) {
  try { $line = $s.ReadLine(); if ($line) { Write-Host $line } } catch {}
}
$s.Close()

Write-Host ""
Write-Host "=============================================="
Write-Host " Done. Look above for one of these:"
Write-Host "   MODE_RUNNING          -> connected, you are good"
Write-Host "   Invalid Auth Token    -> token was wrong"
Write-Host "   Could not connect     -> WiFi name/password wrong"
Write-Host "=============================================="
if (-not $NoPause) { Read-Host "Press Enter to close" }
